name: Build LaTeX document
on: [push, pull_request]
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: Epp.tex
          latexmk_shell_escape: true
      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          make_latest: true
          generate_release_notes: true
          preserve_order: true
          files: src/Epp.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
