name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: |
            all.tex
            chapter1.tex
            chapter2.tex
            chapter3.tex
            chapter4.tex
            chapter5.tex
            chapter6.tex
            chapter7.tex
            chapter8.tex
            chapter9.tex
            chapter10.tex
            chapter11.tex
            chapter12.tex
          latexmk_shell_escape: true
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: PDF
      #     path: main.pdf
